# Network charts

We develop network charts for a circuit connectome. 
We will use a mock circuit to speed up computation.
This will allow us to develop the code for getting the graph data required to make the charts.

## Mock Circuit
We have implemented a `MockCircuit` that follows our BBP circuits as much as 
required by our computations.

In [1]:
import numpy as np
import pandas as pd
from neuro_dmt.models.bluebrain.circuit.model import\
    BlueBrainCircuitModel
from neuro_dmt.models.bluebrain.circuit.mock.circuit import\
    MockCircuit
from neuro_dmt.models.bluebrain.circuit.mock.test.mock_circuit_light import\
    circuit_composition,\
    circuit_connectivity

('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mtype', 'etype', 'synapse_class')
test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 18:07:35>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/__init__.py
	lineno: 	136
	code_context: 	['        __log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 2
with number of excitatory mtypes: 1

test develop mock circuit Logger     

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 18:07:35>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 4
with number of excitatory mtypes: 1

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 18:07:35>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 4
with number of excitatory mtypes: 1

test develop mock circuit Logger                    

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 18:07:35>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 6
with number of excitatory mtypes: 4

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 18:07:35>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 6
with number of excitatory mtypes: 4

test develop mock circuit Logger                    

In [2]:
from neuro_dmt.models.bluebrain.circuit.mock.builder\
    import CircuitBuilder
builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)
cells = builder.get_cell_collection()

In [3]:
connectome = builder.get_connectome(cells)

82304it [05:00, 273.52it/s]
  0%|          | 89/82304 [00:00<01:33, 875.73it/s]

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/builder.py Logger
DEBUGINFO@<2020-02-17 18:07:35>                                                 
Get afferent synapse counts.



100%|██████████| 82304/82304 [02:14<00:00, 613.22it/s] 


In [4]:
#connectome.afferent_adjacency[0]
connections = connectome.connections

100%|██████████| 82304/82304 [00:11<00:00, 7477.81it/s]


In [5]:
connections.tail()

pre_synaptic_cell_gid  post_synaptic_cell_gid  strength
16457146                  80173                   82303         4
16457147                  80417                   82303         1
16457148                  80474                   82303         5
16457149                  80695                   82303         5
16457150                  80718                   82303         4

In [6]:
synapse_counts =\
    connections.set_index(["pre_synaptic_cell_gid", "post_synaptic_cell_gid"])\
               .strength

In [7]:
synapse_counts.sort_index(level=("pre_synaptic_cell_gid", "post_synaptic_cell_gid"))\
              .head()

pre_synaptic_cell_gid  post_synaptic_cell_gid
0                      349                       3
                       415                       4
                       482                       5
                       644                       2
                       1639                      7
Name: strength, dtype: int64

In [8]:
pre_gids =\
    cells.get({"mtype": "L23_MC"}).index.values
print(pre_gids)
post_gids =\
    cells.get({"mtype": "L6_TPC:A"}).index.values
print(post_gids)
connectome.synapse_count.loc[pre_gids]

[  280   281   282 ... 62681 62682 62683]
[14180 14181 14182 ... 78037 78038 78039]


pre_synaptic_cell_gid  post_synaptic_cell_gid
280                    62                        6
                       1021                      4
                       1064                      7
                       1451                      5
                       1461                      3
                                                ..
62683                  80127                     5
                       80485                     5
                       80823                     7
                       81164                     3
                       82177                     4
Name: strength, Length: 262449, dtype: int64

In [9]:
efferent_synapse_count =\
    connectome.synapse_count\
              .loc[pre_gids[0]]\
              .reindex(post_gids)\
              .dropna()
for x in efferent_synapse_count.iteritems():
    print(x)

(14630, 10.0)
(14937, 2.0)
(15282, 6.0)
(15556, 8.0)
(15570, 6.0)
(15593, 5.0)
(15746, 9.0)
(35312, 3.0)
(36097, 5.0)
(36299, 5.0)
(36634, 8.0)
(55483, 5.0)
(55719, 3.0)
(56406, 2.0)
(56753, 6.0)
(75949, 4.0)
(76639, 9.0)
(76648, 6.0)
(77341, 6.0)
(77796, 3.0)
(77969, 2.0)
(78008, 3.0)


In [13]:
from tqdm import tqdm

def iter_connections(pre_gids, post_gids):
    for pre_gid in pre_gids:
        for post_gid, strength in connectome.synapse_count\
                                             .loc[pre_gid]\
                                             .reindex(post_gids)\
                                             .dropna():
            yield (pre_gid, post_gid, strength.strength)

cnxns =\
    pd.DataFrame(
        [x for x in tqdm(connectome.iter_connections(pre_gids, post_gids))],
        columns=["pre_gid", "post_gid", "strength"])
print(len(pre_gids), len(post_gids), cnxns.shape[0])
cnxns.head()

27164it [00:04, 5943.15it/s]

1312 8528 27164


pre_gid  post_gid  strength
0      280     14630      10.0
1      280     14937       2.0
2      280     15282       6.0
3      280     15556       8.0
4      280     15570       6.0

In [22]:
l23_mcs = cells.get({"mtype": "L23_MC"})[["region", "layer", "mtype"]]
print(l23_mcs.head())
print(70*'-')
print(l23_mcs.tail())
print(70*'-')
l23_mcs.index.values

    region  layer   mtype
280   S1HL      2  L23_MC
281   S1HL      2  L23_MC
282   S1HL      2  L23_MC
283   S1HL      2  L23_MC
284   S1HL      2  L23_MC
----------------------------------------------------------------------
      region  layer   mtype
62679   S1Sh      3  L23_MC
62680   S1Sh      3  L23_MC
62681   S1Sh      3  L23_MC
62682   S1Sh      3  L23_MC
62683   S1Sh      3  L23_MC
----------------------------------------------------------------------


array([  280,   281,   282, ..., 62681, 62682, 62683])

In [24]:
cells.get().head()

region  layer      nucleus   mtype etype  morph_class synapse_class  \
0   S1HL      1  not-defined  L1_DAC  bNAC  not-defined           INH   
1   S1HL      1  not-defined  L1_DAC  bNAC  not-defined           INH   
2   S1HL      1  not-defined  L1_DAC  bNAC  not-defined           INH   
3   S1HL      1  not-defined  L1_DAC  bNAC  not-defined           INH   
4   S1HL      1  not-defined  L1_DAC  bNAC  not-defined           INH   

            x          y           z  
0   31.380002  57.823365  102.324811  
1   98.084897  77.580030  243.071500  
2   97.775354  18.319712   10.262522  
3  155.128433  43.487925  138.431076  
4  140.220470   8.947279  239.095651

In [ ]:
bluepy_mock_circuit =\
    MockCircuit.build(
        circuit_composition,
        circuit_connectivity)
mock_circuit_model =\
    BlueBrainCircuitModel(
        bluepy_mock_circuit,
        label="BlueBrainCircuitModelMockLight")

In [ ]:
from neuro_dmt.models.bluebrain.circuit.mock.builder import CircuitBuilder
circuit_builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)
cells =\
    circuit_builder.get_cell_collection().get()
cells.head()

In [ ]:
import pandas as pd
def afferent_connections(self, post_synaptic_cell):
    pre_synaptic_cells =\
        cells.sample(
            self.get_afferent_degree(**post_synaptic_cell))
    return\
        pd.DataFrame([
            {"pre_synaptic_cell_gid": pre_gid,
            "synapse_count": self.get_synapse_count(pre_synaptic_cell,
                                                    post_synaptic_cell)}
            for pre_gid, pre_synaptic_cell in pre_synaptic_cells.iterrows()])

def get_connections(self, cells):
    """
    Afferent connections for a post-synaptic cell
    """
    def _afferent_connections(post_synaptic_cell):
        pre_synaptic_cells =\
            cells.sample(
                self.get_afferent_degree(**post_synaptic_cell))
        return\
            pd.DataFrame([
                {"pre_synaptic_cell_gid": pre_gid,
                 "synapse_count": self.get_synapse_count(pre_synaptic_cell,
                                                            post_synaptic_cell)}
                for pre_gid, pre_synaptic_cell in pre_synaptic_cells.iterrows()])

    return\
        pd.concat([
            _afferent_connections(post_synaptic_cell).assign(
                post_synaptic_cell_gid=post_gid)
            for post_gid, post_synaptic_cell in cells.iterrows()])

In [ ]:
#afferent_connections(circuit_connectivity, cells.iloc[0])
cnxns = get_connections(circuit_connectivity, cells)

In [ ]:
degree =\
    cells.sa
pd.DataFrame([
    {"pre_synaptic_cell_gid": pre_gid,
     "synapse_count": circuit_connectivity.get_synapse_count(pre_synaptic_cell,
                                                             post_synaptic_cell)}
    for pre_gid, pre_synaptic_cell in cells.sample(degree).iterrows()])

In [ ]:
import pandas as pd
def afferent_connections(post_synaptic_cell):
    degree =\
        circuit_connectivity.get_afferent_degree(**post_synaptic_cell)
    return\
        pd.DataFrame([
            {"pre_synaptic_cell_gid": pre_gid,
             "synapse_count": circuit_connectivity.get_synapse_count(
                                 pre_synaptic_cell, post_synaptic_cell)}
            for pre_gid, pre_synaptic_cell in cells.sample(degree).iterrows()])
                    

In [ ]:
post_synaptic_cell = cells.iloc[0]
pre_gids =\
    np.sort(np.random.choice(
        cells.index,
        circuit_connectivity.get_afferent_degree(**post_synaptic_cell)))
print(len(pre_gids))
print(pre_gids.shape)
#cells.loc[pre_gids]

In [ ]:
pre_synaptic_cells =\
    cells.sample(
        circuit_connectivity.get_afferent_degree(**post_synaptic_cell))
print(pre_synaptic_cells.head()[["region", "layer", "mtype"]])
print(70*"-")
for pre_gid, pre_cell in pre_synaptic_cells.head().iterrows():
    print(pre_gid, pre_cell.region, pre_cell.layer, pre_cell.mtype)

In [ ]:
afferent_connections(post_synaptic_cell)