In [ ]:
# Network charts

We develop network charts for a circuit connectome. 
We will use a mock circuit to speed up computation.
This will allow us to develop the code for getting the graph data required to make the charts.

## Mock Circuit
We have implemented a `MockCircuit` that follows our BBP circuits as much as 
required by our computations.

In [1]:
import numpy as np
import pandas as pd
from neuro_dmt.models.bluebrain.circuit.model import\
    BlueBrainCircuitModel
from neuro_dmt.models.bluebrain.circuit.mock.circuit import\
    MockCircuit
from neuro_dmt.models.bluebrain.circuit.mock.test.mock_circuit_light import\
    circuit_composition,\
    circuit_connectivity

('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mtype', 'etype', 'synapse_class')
test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/__init__.py
	lineno: 	136
	code_context: 	['        __log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 2
with number of excitatory mtypes: 1

test develop mock circuit Logger     

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 4
with number of excitatory mtypes: 1

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 4
with number of excitatory mtypes: 1

test develop mock circuit Logger                    

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 6
with number of excitatory mtypes: 4

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 6
with number of excitatory mtypes: 4

test develop mock circuit Logger                    

In [2]:
from neuro_dmt.models.bluebrain.circuit.mock.builder\
    import CircuitBuilder
builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)
cells = builder.get_cell_collection()

In [3]:
connectome = builder.get_connectome(cells)

82304it [02:14, 612.45it/s]
  0%|          | 106/82304 [00:00<01:17, 1055.67it/s]

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/builder.py Logger
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Get afferent synapse counts.



100%|██████████| 82304/82304 [01:16<00:00, 1076.78it/s]


In [4]:
#connectome.afferent_adjacency[0]
connections = connectome.connections

100%|██████████| 82304/82304 [00:08<00:00, 9717.79it/s]


In [5]:
connections.tail()

pre_synaptic_cell_gid  post_synaptic_cell_gid  strength
16459788                  80742                   82303         5
16459789                  80863                   82303         5
16459790                  81021                   82303         7
16459791                  81242                   82303         5
16459792                  81392                   82303         5

In [6]:
pre_gids =\
    cells.get({"mtype": "L23_MC"}).index.values
print(pre_gids)
post_gids =\
    cells.get({"mtype": "L6_TPC:A"}).index.values
print(post_gids)

[  280   281   282 ... 62681 62682 62683]
[14180 14181 14182 ... 78037 78038 78039]


In [7]:
from tqdm import tqdm

def iter_connections(pre_gids, post_gids):
    for pre_gid in pre_gids:
        for post_gid, strength in connectome.synapse_count\
                                             .loc[pre_gid]\
                                             .reindex(post_gids)\
                                             .dropna():
            yield (pre_gid, post_gid, strength.strength)

cnxns =\
    pd.DataFrame(
        [x for x in tqdm(connectome.iter_connections(pre_gids, post_gids))],
        columns=["pre_gid", "post_gid", "strength"])
print(len(pre_gids), len(post_gids), cnxns.shape[0])
cnxns.head()

27298it [00:21, 1265.78it/s]


1312 8528 27298


pre_gid  post_gid  strength
0      280     14640       5.0
1      280     14797       3.0
2      280     15983       3.0
3      280     16130       4.0
4      280     34866       2.0

In [4]:
bluepy_mock_circuit =\
    MockCircuit.build(
        circuit_composition,
        circuit_connectivity)
mock_circuit_model =\
    BlueBrainCircuitModel(
        bluepy_mock_circuit,
        label="BlueBrainCircuitModelMockLight")

82304it [02:14, 614.14it/s]
  0%|          | 113/82304 [00:00<01:13, 1124.52it/s]

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/builder.py Logger
DEBUGINFO@<2020-02-17 20:05:16>                                                 
Get afferent synapse counts.



100%|██████████| 82304/82304 [01:18<00:00, 1052.79it/s]


In [12]:
iter_connections =\
    mock_circuit_model.connectome\
                      .iter_connections(post=[0])
connections =\
    np.array([c for c in iter_connections])

In [13]:
connections

array([[  805,     0,     6],
       [  977,     0,     2],
       [ 1067,     0,     3],
       [ 1774,     0,     5],
       [ 1899,     0,     3],
       [ 2083,     0,     7],
       [ 2096,     0,     6],
       [ 2755,     0,     6],
       [ 2790,     0,     6],
       [ 3362,     0,     4],
       [ 3900,     0,     7],
       [ 4003,     0,     4],
       [ 4372,     0,     5],
       [ 4498,     0,     8],
       [ 4740,     0,     7],
       [ 5009,     0,     7],
       [ 5201,     0,     3],
       [ 5508,     0,     3],
       [ 5811,     0,     8],
       [ 6614,     0,     2],
       [ 6886,     0,     6],
       [ 7267,     0,     5],
       [ 7411,     0,     4],
       [ 7694,     0,     6],
       [ 7717,     0,     2],
       [ 8670,     0,     5],
       [10291,     0,     4],
       [10554,     0,     6],
       [10698,     0,     6],
       [10730,     0,     5],
       [10732,     0,     5],
       [10741,     0,     3],
       [10760,     0,     7],
       [11

In [7]:
from neuro_dmt.models.bluebrain.circuit.adapter import BlueBrainCircuitAdapter
adapter = BlueBrainCircuitAdapter()
adapter.get_afferent_connections(
    mock_circuit_model,
    mock_circuit_model.cells.iloc[10])


pre_gid  strength
0        259         4
1        299         4
2        850         5
3       1427         2
4       1942         8
5       2048         2
6       2534         2
7       2596         4
8       3062         3
9       3067         5
10      3754         5
11      4060         6
12      4098         4
13      4549         3
14      4570         5
15      5003         3
16      5004         2
17      5080         5
18      5222         6
19      5591         6
20      6101         5
21      6127         6
22      6183         2
23      6279         5
24      6627        10
25      8096         6
26      8280         4
27      8394         7
28      9374         5
29      9482         1
..       ...       ...
177    70009         1
178    70427         8
179    70461         8
180    70483         2
181    70520         6
182    71012         3
183    71338         3
184    71402         6
185    71408         3
186    73030         4
187    73081         5
188    73927        12
189    73952         7
190    73981         7
191    74627         3
192    74810         8
193    74818         4
194    75728         4
195    76247         8
196    76485         7
197    78335         6
198    78429         6
199    78904         3
200    78938         2
201    79110         5
202    80177         3
203    80479         4
204    81106         3
205    81225         4
206    81316         3

[207 rows x 2 columns]

In [ ]:
from neuro_dmt.models.bluebrain.circuit.mock.builder import CircuitBuilder
circuit_builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)
cells =\
    circuit_builder.get_cell_collection().get()
cells.head()

In [ ]:
import pandas as pd
def afferent_connections(self, post_synaptic_cell):
    pre_synaptic_cells =\
        cells.sample(
            self.get_afferent_degree(**post_synaptic_cell))
    return\
        pd.DataFrame([
            {"pre_synaptic_cell_gid": pre_gid,
            "synapse_count": self.get_synapse_count(pre_synaptic_cell,
                                                    post_synaptic_cell)}
            for pre_gid, pre_synaptic_cell in pre_synaptic_cells.iterrows()])

def get_connections(self, cells):
    """
    Afferent connections for a post-synaptic cell
    """
    def _afferent_connections(post_synaptic_cell):
        pre_synaptic_cells =\
            cells.sample(
                self.get_afferent_degree(**post_synaptic_cell))
        return\
            pd.DataFrame([
                {"pre_synaptic_cell_gid": pre_gid,
                 "synapse_count": self.get_synapse_count(pre_synaptic_cell,
                                                            post_synaptic_cell)}
                for pre_gid, pre_synaptic_cell in pre_synaptic_cells.iterrows()])

    return\
        pd.concat([
            _afferent_connections(post_synaptic_cell).assign(
                post_synaptic_cell_gid=post_gid)
            for post_gid, post_synaptic_cell in cells.iterrows()])

In [ ]:
#afferent_connections(circuit_connectivity, cells.iloc[0])
cnxns = get_connections(circuit_connectivity, cells)

In [ ]:
degree =\
    cells.sa
pd.DataFrame([
    {"pre_synaptic_cell_gid": pre_gid,
     "synapse_count": circuit_connectivity.get_synapse_count(pre_synaptic_cell,
                                                             post_synaptic_cell)}
    for pre_gid, pre_synaptic_cell in cells.sample(degree).iterrows()])

In [ ]:
import pandas as pd
def afferent_connections(post_synaptic_cell):
    degree =\
        circuit_connectivity.get_afferent_degree(**post_synaptic_cell)
    return\
        pd.DataFrame([
            {"pre_synaptic_cell_gid": pre_gid,
             "synapse_count": circuit_connectivity.get_synapse_count(
                                 pre_synaptic_cell, post_synaptic_cell)}
            for pre_gid, pre_synaptic_cell in cells.sample(degree).iterrows()])
                    

In [ ]:
post_synaptic_cell = cells.iloc[0]
pre_gids =\
    np.sort(np.random.choice(
        cells.index,
        circuit_connectivity.get_afferent_degree(**post_synaptic_cell)))
print(len(pre_gids))
print(pre_gids.shape)
#cells.loc[pre_gids]

In [ ]:
pre_synaptic_cells =\
    cells.sample(
        circuit_connectivity.get_afferent_degree(**post_synaptic_cell))
print(pre_synaptic_cells.head()[["region", "layer", "mtype"]])
print(70*"-")
for pre_gid, pre_cell in pre_synaptic_cells.head().iterrows():
    print(pre_gid, pre_cell.region, pre_cell.layer, pre_cell.mtype)

In [ ]:
afferent_connections(post_synaptic_cell)