# Test Develop Mock Circuit

In [1]:
from neuro_dmt.models.bluebrain.circuit.mock.cells import Position, Cell

In [2]:
p = Position(X = 1., Y = 1., Z = 1.)
print(p.as_tuple)
print(p.value)

random_positions =\
    Position.sample(
        (np.array((-1., -1., -1.)), np.array((1., 1., 1.))),
        n = 3)
print(random_positions)

(1.0, 1.0, 1.0)
[1. 1. 1.]
[[-0.66419228 -0.45378102 -0.28074639]
 [-0.05017034  0.0400958  -0.35899231]
 [-0.68340663 -0.81066059 -0.28387009]]


In [3]:
example_cell =\
    Cell(
        layer=1,
        position=Position(X=1., Y=2., Z=3.),
        mtype="L23_BTC")

In [4]:
example_cell.as_dict

{'region': 'brain',
 'layer': 1,
 'nucleus': 'not-defined',
 'mtype': 'L23_BTC',
 'etype': 'not-defined',
 'morph_class': 'not-defined',
 'synapse_class': 'INH',
 'x': 1.0,
 'y': 2.0,
 'z': 3.0}

In [5]:
from neuro_dmt.models.bluebrain.circuit.mock.test_develop\
    import circuit_composition
circuit_composition.cell_density.head()

error         mean
mtype  layer                    
L1_DAC 1        0.0  3094.333333
       2        0.0     0.000000
       3        0.0     0.000000
       4        0.0     0.000000
       5        0.0     0.000000

In [6]:
from neuro_dmt.models.bluebrain.circuit.mock.cells import CircuitBuilder

In [7]:
cb = CircuitBuilder(composition=circuit_composition)

In [8]:
cb.get_cell_density(mtype="L1_DAC", layer=1)

error         mean
mtype  layer                    
L1_DAC 1        0.0  3094.333333

In [9]:
print(circuit_composition.cell_density.head())
print(cb.get_number_cells(1, "L1_DAC"))

              error         mean
mtype  layer                    
L1_DAC 1        0.0  3094.333333
       2        0.0     0.000000
       3        0.0     0.000000
       4        0.0     0.000000
       5        0.0     0.000000
23


In [10]:
circuit_cells = cb.get_cells()

In [11]:
import pandas as pd
circuit_cells_df =\
    pd.DataFrame([
        cell.as_dict for cell in circuit_cells])
print("number of cells {}".format(circuit_cells_df.shape[0]))
print(circuit_cells_df.head())

number of cells 12237
         etype  layer  morph_class   mtype      nucleus region synapse_class  \
0  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
1  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
2  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
3  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
4  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   

            x            y           z  
0  183.371826  1808.585641  101.187793  
1    9.188315  1732.893566   21.969420  
2  207.532652  1723.292299  207.808889  
3   37.760431  1730.793564  116.190053  
4  196.446443  1803.342314  152.953004  


In [ ]:
b = 230.
2 * np.cos(np.pi / 3.) * b

In [ ]:
np.sqrt(6 * b * b * np.sin(np.pi / 3))

In [ ]:
from bluepy.geometry import roi

In [ ]:
roi.ROI([1., 2., 3.]).bbox

In [ ]:
np.random.random([4, 3])


In [ ]:
t = tuple
t((1,2,2))

In [ ]:
t = np.array
t((1,2,2))

In [ ]:
np.random.random_sample([2,3])

In [ ]:
np.random.random([2,3])

In [ ]:
def lazy(instance_property):
    """
    Make instance property lazy.
    """
    print("instance property name is {} ".format(instance_property.__name__))
    property_name =\
        "_{}".format(instance_property.__name__)
    @property
    def effective(instance):
        if not hasattr(instance, property_name):
            print("cache")
            setattr(
                instance,
                property_name,
                instance_property(instance))
        print("return cached")
        return getattr(instance, property_name)
    return effective

In [ ]:
class A:
    def __init__(self, x):
        self.x = x
        
    @lazy
    def y(self):
        return self.x * self.x

In [ ]:
a = A(2)
print("lazy y", a.y)

In [ ]:
a.y

In [ ]:
a.x = 3
a.y

In [ ]:
x, y = *np.array([1,2])