# Test Develop Mock Circuit

In [1]:
import numpy as np
import pandas as pd
from neuro_dmt.models.bluebrain.circuit.mock.cell import Cell

In [2]:
from neuro_dmt.models.bluebrain.circuit.geometry import Position
p = Position(X = 1., Y = 1., Z = 1.)
print(p.as_tuple)
print(p.value)

random_positions =\
    Position.sample(
        (np.array((-1., -1., -1.)), np.array((1., 1., 1.))),
        n = 3)
print(random_positions)

(1.0, 1.0, 1.0)
[1. 1. 1.]
[[-0.56492934 -0.26705398  0.28233447]
 [ 0.39493214 -0.48384451 -0.45060693]
 [ 0.87291311  0.05149363 -0.36150597]]


In [3]:
example_cell =\
    Cell(
        layer=1,
        position=Position(X=1., Y=2., Z=3.),
        mtype="L23_BTC")
example_cell.as_dict

{'region': 'brain',
 'layer': 1,
 'nucleus': 'not-defined',
 'mtype': 'L23_BTC',
 'etype': 'not-defined',
 'morph_class': 'not-defined',
 'synapse_class': 'INH',
 'x': 1.0,
 'y': 2.0,
 'z': 3.0}

In [4]:
from neuro_dmt.models.bluebrain.circuit.mock.test_develop\
    import circuit_composition, circuit_connectivity
circuit_composition.cell_density.head()

mean  std
mtype  layer                  
L1_DAC 1      3094.333333  0.0
       2         0.000000  0.0
       3         0.000000  0.0
       4         0.000000  0.0
       5         0.000000  0.0

In [5]:
from neuro_dmt.models.bluebrain.circuit.mock import CircuitBuilder
test_circuit_builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)
test_circuit_builder.get_cell_density( mtype="L1_DAC", layer=1 )

mean  std
mtype  layer                  
L1_DAC 1      3094.333333  0.0

In [6]:
print(circuit_composition.cell_density.loc["L1_DAC"])
print(test_circuit_builder.get_number_cells(1, "L1_DAC"))

              mean  std
layer                  
1      3094.333333  0.0
2         0.000000  0.0
3         0.000000  0.0
4         0.000000  0.0
5         0.000000  0.0
6         0.000000  0.0
23


In [7]:
circuit_cells = test_circuit_builder.get_cells()

In [8]:
import pandas as pd
circuit_cells_df =\
    pd.DataFrame([
        cell.as_dict for cell in circuit_cells])
print("number of cells {}".format(circuit_cells_df.shape[0]))
print(circuit_cells_df.head())

number of cells 12237
         etype  layer  morph_class   mtype      nucleus region synapse_class  \
0  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
1  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
2  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
3  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
4  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   

            x            y           z  
0   43.878373  1723.686762   76.718120  
1  228.453226  1751.511934   94.794313  
2  213.767105  1771.889205   63.549876  
3   19.995182  1800.157011  144.579105  
4   90.141868  1793.903716  101.078179  


In [9]:
cell_collection = test_circuit_builder.get_cell_collection()
cell_collection.get(1, "mtype")

'L1_DAC'

In [10]:
cell_collection.get([1,2], properties=["mtype", "etype"])

mtype        etype
1  L1_DAC  not-defined
2  L1_DAC  not-defined

In [11]:
from neuro_dmt.models.bluebrain.circuit.mock.circuit import MockCircuit
mock_circuit =\
    MockCircuit.build(
        circuit_composition,
        circuit_connectivity)

In [13]:
mock_cells = mock_circuit.cells
mock_cells.get([1, 3000], "mtype")

1       L1_DAC
3000     L4_PC
Name: mtype, dtype: object

In [16]:
mock_circuit.connectome.afferent_gids(2)

array([    1,     4,     7, ..., 12210, 12217, 12218])

In [17]:
mock_circuit.connectome.efferent_gids(4)

array([    2,     3,     8, ..., 12233, 12234, 12235])

In [18]:
mock_circuit.connectome.afferent_gids(14)

array([    3,     4,    12, ..., 12229, 12230, 12233])

In [19]:
mock_circuit.connectome.afferent_adjacency[0]

array([[    9,     7],
       [   10,     3],
       [   15,     5],
       ...,
       [12230,     7],
       [12231,     6],
       [12235,     6]])

In [ ]:
ds = pd.Series(dict(x=1, y=2, z=3))
ds['x']

In [ ]:
df = pd.DataFrame(dict(
    x=[1,2,23],
    y=[2,3,4],
    z=[123,12134,12]))
df.loc[[1,2]]['x'].values

In [ ]:
from collections import Mapping
issubclass(Mapping, dict)
issubclass(dict, Mapping)

In [ ]:
set(x for x in range(10))