# Test Develop Mock Circuit

In [1]:
import numpy as np
import pandas as pd
from neuro_dmt.models.bluebrain.circuit.mock.cell import Cell

In [2]:
from neuro_dmt.models.bluebrain.circuit.geometry import Position
p = Position(X = 1., Y = 1., Z = 1.)
print(p.as_tuple)
print(p.value)

random_positions =\
    Position.sample(
        (np.array((-1., -1., -1.)), np.array((1., 1., 1.))),
        n = 3)
print(random_positions)

(1.0, 1.0, 1.0)
[1. 1. 1.]
[[ 0.80773396  0.47342512  0.58733637]
 [-0.69855092 -0.3524589  -0.95444981]
 [ 0.26400938 -0.43636225 -0.41041609]]


In [3]:
example_cell =\
    Cell(
        layer=1,
        position=Position(X=1., Y=2., Z=3.),
        mtype="L23_BTC")
example_cell.as_dict

{'region': 'brain',
 'layer': 1,
 'nucleus': 'not-defined',
 'mtype': 'L23_BTC',
 'etype': 'not-defined',
 'morph_class': 'not-defined',
 'synapse_class': 'INH',
 'x': 1.0,
 'y': 2.0,
 'z': 3.0}

In [4]:
from neuro_dmt.models.bluebrain.circuit.mock.test_develop\
    import circuit_composition, circuit_connectivity
circuit_composition.cell_density.head()

mean  std
mtype  layer                  
L1_DAC 1      3094.333333  0.0
       2         0.000000  0.0
       3         0.000000  0.0
       4         0.000000  0.0
       5         0.000000  0.0

In [5]:
from neuro_dmt.models.bluebrain.circuit.mock import CircuitBuilder
test_circuit_builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)
test_circuit_builder.get_cell_density( mtype="L1_DAC", layer=1 )

mean  std
mtype  layer                  
L1_DAC 1      3094.333333  0.0

In [6]:
print(circuit_composition.cell_density.loc["L1_DAC"])
print(test_circuit_builder.get_number_cells(1, "L1_DAC"))

              mean  std
layer                  
1      3094.333333  0.0
2         0.000000  0.0
3         0.000000  0.0
4         0.000000  0.0
5         0.000000  0.0
6         0.000000  0.0
23


In [7]:
circuit_cells = test_circuit_builder.get_cells()

In [8]:
import pandas as pd
circuit_cells_df =\
    pd.DataFrame([
        cell.as_dict for cell in circuit_cells])
print("number of cells {}".format(circuit_cells_df.shape[0]))
print(circuit_cells_df.head())

number of cells 12237
         etype  layer  morph_class   mtype      nucleus region synapse_class  \
0  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
1  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
2  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
3  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
4  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   

            x            y           z  
0  192.602779  1794.304344    3.383522  
1  224.076694  1763.255213   69.977905  
2  225.658088  1839.234586   33.363346  
3  235.191749  1769.417390   78.271956  
4   88.520229  1823.055178  116.645568  


In [9]:
cell_collection = test_circuit_builder.get_cell_collection()
cell_collection.get(1, "mtype")

'L1_DAC'

In [10]:
cell_collection.get([1,2], properties=["mtype", "etype"])

mtype        etype
1  L1_DAC  not-defined
2  L1_DAC  not-defined

In [11]:
from neuro_dmt.models.bluebrain.circuit.mock.circuit import MockCircuit
mock_circuit =\
    MockCircuit.build(
        circuit_composition,
        circuit_connectivity)

In [12]:
mock_cells = mock_circuit.cells
mock_cells.get([1, 3000], "mtype")

1       L1_DAC
3000     L4_PC
Name: mtype, dtype: object

In [13]:
mock_circuit.connectome.afferent_gids(2)

array([    1,     7,    10, ..., 12228, 12233, 12235])

In [14]:
mock_circuit.connectome.efferent_gids(4)

array([    4,    17,    19, ..., 12229, 12232, 12234])

In [15]:
mock_circuit.connectome.afferent_gids(14)

array([    0,     9,    12, ..., 12224, 12225, 12228])

In [16]:
mock_circuit.connectome.afferent_adjacency[0]

array([[   15,     6],
       [   19,     4],
       [   24,     3],
       ...,
       [12216,     3],
       [12217,     5],
       [12225,     2]])

In [17]:
ds = pd.Series(dict(x=1, y=2, z=3))
ds['x']

1

In [18]:
df = pd.DataFrame(dict(
    x=[1,2,23],
    y=[2,3,4],
    z=[123,12134,12]))
df.loc[[1,2]]['x'].values

array([ 2, 23])

In [19]:
from collections import Mapping
issubclass(Mapping, dict)
issubclass(dict, Mapping)

True

In [20]:
set(x for x in range(10))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [21]:
from enum import Enum
class Ahah(Enum):
    oh = 1
    ohho = 2
    ah = 3
    ahah = 4
    ahha = 5
    ohah = 6

In [25]:
for x in Ahah:
    print(x)

Ahah.oh
Ahah.ohho
Ahah.ah
Ahah.ahah
Ahah.ahha
Ahah.ohah


In [26]:
from bluepy.v2.enums import Synapse as SynapseProperty
for x in SynapseProperty:
    print(x)

Synapse.PRE_GID
Synapse.POST_GID
Synapse.AXONAL_DELAY
Synapse.D_SYN
Synapse.DTC
Synapse.F_SYN
Synapse.G_SYNX
Synapse.NRRP
Synapse.TYPE
Synapse.U_SYN
Synapse.PRE_BRANCH_ORDER
Synapse.PRE_NEURITE_DISTANCE
Synapse.PRE_SECTION_DISTANCE
Synapse.PRE_SECTION_ID
Synapse.POST_BRANCH_ORDER
Synapse.POST_BRANCH_TYPE
Synapse.POST_NEURITE_DISTANCE
Synapse.POST_SECTION_DISTANCE
Synapse.POST_SECTION_ID
Synapse.PRE_X_CENTER
Synapse.PRE_Y_CENTER
Synapse.PRE_Z_CENTER
Synapse.PRE_X_CONTOUR
Synapse.PRE_Y_CONTOUR
Synapse.PRE_Z_CONTOUR
Synapse.POST_X_CENTER
Synapse.POST_Y_CENTER
Synapse.POST_Z_CENTER
Synapse.POST_X_CONTOUR
Synapse.POST_Y_CONTOUR
Synapse.POST_Z_CONTOUR
Synapse.TOUCH_DISTANCE


In [31]:
isinstance(np.int(1), (int, np.integer))

True