# Test Develop Mock Circuit

In [2]:
from neuro_dmt.models.bluebrain.circuit.mock.cell import Cell

In [3]:
from neuro_dmt.models.bluebrain.circuit.geometry import Position
p = Position(X = 1., Y = 1., Z = 1.)
print(p.as_tuple)
print(p.value)

random_positions =\
    Position.sample(
        (np.array((-1., -1., -1.)), np.array((1., 1., 1.))),
        n = 3)
print(random_positions)

(1.0, 1.0, 1.0)
[1. 1. 1.]
[[ 0.10962297  0.45293786 -0.20395631]
 [ 0.851341    0.24240521  0.81023499]
 [ 0.73840723  0.08342335  0.16595602]]


In [ ]:
example_cell =\
    Cell(
        layer=1,
        position=Position(X=1., Y=2., Z=3.),
        mtype="L23_BTC")

In [ ]:
example_cell.as_dict

In [ ]:
from neuro_dmt.models.bluebrain.circuit.mock.test_develop\
    import circuit_composition
circuit_composition.cell_density.head()

In [ ]:
from neuro_dmt.models.bluebrain.circuit.mock import CircuitBuilder

In [ ]:
cb = CircuitBuilder(composition=circuit_composition)

In [ ]:
cb.get_cell_density(mtype="L1_DAC", layer=1)

In [ ]:
print(circuit_composition.cell_density.head())
print(cb.get_number_cells(1, "L1_DAC"))

In [ ]:
circuit_cells = cb.get_cells()

In [ ]:
import pandas as pd
circuit_cells_df =\
    pd.DataFrame([
        cell.as_dict for cell in circuit_cells])
print("number of cells {}".format(circuit_cells_df.shape[0]))
print(circuit_cells_df.head())

In [30]:
import pandas as pd
df = pd.DataFrame([
    dict(layer=1, mtype="L23_BC", x=1., y=2., z=3.),
    dict(layer=2, mtype="L23_BTC", x=1., y=4., z=2.),
    dict(layer=3, mtype="L23_BTC", x=1., y=4., z=2.)])

In [34]:
print(df[df.layer.apply(lambda l: l in set([1,2]))])
df[np.logical_and(
    df.layer.apply(lambda l: l in set([1,3])),
    df.mtype == "L23_BTC")]

   layer    mtype    x    y    z
0      1   L23_BC  1.0  2.0  3.0
1      2  L23_BTC  1.0  4.0  2.0


layer    mtype    x    y    z
2      3  L23_BTC  1.0  4.0  2.0

In [11]:
[l in set([1,2]) for l in df.layer]

[True, True]

In [39]:
df.layer.apply(lambda l: l in set([1,2]))

0     True
1     True
2    False
Name: layer, dtype: bool

In [37]:
pd.Series(10 * [True])

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [47]:
np.array(df.index)

array([0, 1, 2])

In [66]:
for gid, cell_properties in df.iterrows():
    print("({}) {}".format(gid, cell_properties.to_dict()))

(0) {'layer': 1, 'mtype': 'L23_BC', 'x': 1.0, 'y': 2.0, 'z': 3.0}
(1) {'layer': 2, 'mtype': 'L23_BTC', 'x': 1.0, 'y': 4.0, 'z': 2.0}
(2) {'layer': 3, 'mtype': 'L23_BTC', 'x': 1.0, 'y': 4.0, 'z': 2.0}


In [62]:
np.random.choice(range(10), 20, replace=True)

array([8, 6, 7, 2, 8, 2, 9, 3, 3, 0, 0, 0, 8, 8, 6, 8, 9, 0, 8, 7])