# Test Develop Mock Circuit

In [1]:
import numpy as np
import pandas as pd
from neuro_dmt.models.bluebrain.circuit.mock.cell import Cell

In [2]:
from neuro_dmt.models.bluebrain.circuit.geometry import Position
p = Position(X = 1., Y = 1., Z = 1.)
print(p.as_tuple)
print(p.value)

random_positions =\
    Position.sample(
        (np.array((-1., -1., -1.)), np.array((1., 1., 1.))),
        n = 3)
print(random_positions)

(1.0, 1.0, 1.0)
[1. 1. 1.]
[[ 0.61460123 -0.78212686 -0.80535525]
 [ 0.21507985 -0.27515882  0.21698577]
 [ 0.66321446 -0.03132215 -0.26511505]]


In [3]:
example_cell =\
    Cell(
        layer=1,
        position=Position(X=1., Y=2., Z=3.),
        mtype="L23_BTC")

In [4]:
example_cell.as_dict

{'etype': 'not-defined',
 'layer': 1,
 'morph_class': 'not-defined',
 'mtype': 'L23_BTC',
 'nucleus': 'not-defined',
 'region': 'brain',
 'synapse_class': 'INH',
 'x': 1.0,
 'y': 2.0,
 'z': 3.0}

In [5]:
from neuro_dmt.models.bluebrain.circuit.mock.test_develop\
    import circuit_composition, circuit_connectivity
circuit_composition.cell_density.head()

error         mean
mtype  layer                    
L1_DAC 1        0.0  3094.333333
       2        0.0     0.000000
       3        0.0     0.000000
       4        0.0     0.000000
       5        0.0     0.000000

In [6]:
from neuro_dmt.models.bluebrain.circuit.mock import CircuitBuilder

In [7]:
test_circuit_builder =\
    CircuitBuilder(
        composition=circuit_composition,
        connectivity=circuit_connectivity)

In [8]:
test_circuit_builder.get_cell_density( mtype="L1_DAC", layer=1 )

error         mean
mtype  layer                    
L1_DAC 1        0.0  3094.333333

In [9]:
print(circuit_composition.cell_density.head())
print(test_circuit_builder.get_number_cells(1, "L1_DAC"))

              error         mean
mtype  layer                    
L1_DAC 1        0.0  3094.333333
       2        0.0     0.000000
       3        0.0     0.000000
       4        0.0     0.000000
       5        0.0     0.000000
23


In [10]:
circuit_cells = test_circuit_builder.get_cells()

In [11]:
import pandas as pd
circuit_cells_df =\
    pd.DataFrame([
        cell.as_dict for cell in circuit_cells])
print("number of cells {}".format(circuit_cells_df.shape[0]))
print(circuit_cells_df.head())

number of cells 12237
         etype  layer  morph_class   mtype      nucleus region synapse_class  \
0  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
1  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
2  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
3  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   
4  not-defined      1  not-defined  L1_DAC  not-defined  brain           INH   

            x            y           z  
0  209.321891  1754.609554   15.128374  
1  134.897416  1810.075714   79.596434  
2  137.541468  1719.704839  220.045465  
3  108.502245  1800.796284  176.947519  
4  111.910265  1813.429517   80.053781  


In [13]:
cell_collection = test_circuit_builder.get_cell_collection()
cell_collection.get(1, "mtype")

'L1_DAC'

In [19]:
cell_collection.get([1,2], properties=["mtype", "etype"])

mtype        etype
1  L1_DAC  not-defined
2  L1_DAC  not-defined

In [20]:
from neuro_dmt.models.bluebrain.circuit.mock.circuit import MockCircuit
mock_circuit =\
    MockCircuit.build(
        circuit_composition,
        circuit_connectivity)

In [ ]:
mock_cells = mock_circuit.cells
mock_cells.get((1, 3000), "mtype")

In [ ]:
isinstance((1,2), (list, np.array))

In [ ]:
mock_circuit.connectome.afferent_gids(2)

In [ ]:
mock_circuit.connectome.efferent_gids(4)

In [ ]:
mock_circuit.connectome.afferent_gids(14)

In [ ]:
mock_circuit.connectome.afferent_adjacency[0]

In [ ]:
import six
six.integer_types

In [ ]:
ds = pd.Series(dict(x=1, y=2, z=3))
ds['x']

In [24]:
df = pd.DataFrame(dict(
    x=[1,2,23],
    y=[2,3,4],
    z=[123,12134,12]))
df.loc[[1,2]]['x'].values

array([ 2, 23])

In [ ]:
df