# Connectome Analyses

We develop tools to analyze a circuit model's connectome.

In [1]:
import os
import numpy as np
import pandas as pd
from neuro_dmt.library.users.visood.sscx_dissemination.analyses.composition\
    import CompositionAnalysesSuite
from neuro_dmt.library.users.visood.sscx_dissemination.analyses.connectome\
    import ConnectomeAnalysesSuite
from neuro_dmt.models.bluebrain.circuit.atlas import\
    BlueBrainCircuitAtlas
from neuro_dmt.models.bluebrain.circuit.model import\
    BlueBrainCircuitModel,\
    CircuitProvenance
from neuro_dmt.models.bluebrain.circuit.adapter import\
    BlueBrainCircuitAdapter

('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mtype', 'etype', 'synapse_class')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi', 'mtype', 'etype', 'synapse_class', 'postsynaptic', 'presynaptic')
('region', 'layer', 'depth', 'height', 'mesocolumn', 'hypercolumn', 'roi')


In [2]:
project =\
    os.path.join(
        "/gpfs/bbp.cscs.ch/project")
proj_sscx_diss=\
    os.path.join(
        project,
        "proj83")
data_sscx_diss=\
    os.path.join(
        proj_sscx_diss,
        "data")
atlases_sscx_diss=\
    os.path.join(
        data_sscx_diss,
        "atlas/S1/MEAN")
circuits_sscx_diss=\
    os.path.join(
        proj_sscx_diss,
        "circuits")
atlas_bio_m =\
    BlueBrainCircuitAtlas(
        path=os.path.join(
                atlases_sscx_diss, "P14-MEAN"))
path_bio_m =\
    os.path.join(
        circuits_sscx_diss,
        "Bio_M/20191206")
circuit_bio_m =\
    BlueBrainCircuitModel(
        path_circuit_data=path_bio_m,
            provenance=CircuitProvenance(
                label="SSCxRatDisseminationBioM",
                authors=["BBP Team"],
                release_date="20191212",
                uri=path_bio_m,
                animal="Wistar Rat",
                age="P14",
                brain_region="SSCx"))
adapter =\
    BlueBrainCircuitAdapter()
suite_connectome_analyses =\
    ConnectomeAnalysesSuite(
        sample_size=20)

## Mock circuit

We will use a mock-circuit to test-develop connectome analyses.

In [3]:
from neuro_dmt.models.bluebrain.circuit.mock.circuit import\
    MockCircuit
from neuro_dmt.models.bluebrain.circuit.mock.test.mock_circuit_light import\
    circuit_composition,\
    circuit_connectivity

bluepy_mock_circuit =\
    MockCircuit.build(
        circuit_composition,
        circuit_connectivity)
mock_circuit_model =\
    BlueBrainCircuitModel(
        bluepy_mock_circuit,
        label="BlueBrainCircuitModelMockLight")

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/__init__.py
	lineno: 	136
	code_context: 	['        __log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 2
with number of excitatory mtypes: 1

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/__init__.py
	lineno: 	136
	code_context: 	['        __log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 3
with number of excitatory mtypes: 1

test develop mock circuit Logger                                    

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 5
with number of excitatory mtypes: 3

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 5
with number of excitatory mtypes: 3

test develop mock circuit Logger                    

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 6
with number of excitatory mtypes: 4

test develop mock circuit Logger                                                
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Traceback:
	filename: 	/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/test/mock_circuit_light.py
	lineno: 	104
	code_context: 	['        log.get_source_info(),\n']
	index: 0

get excitatory cell density for layer 6
with number of excitatory mtypes: 4

test develop mock circuit Logger                    

102it [00:00, 482.29it/s]

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/models/bluebrain/circuit/mock/builder.py Logger
DEBUGINFO@<2020-02-17 22:55:05>                                                 
Build the (mock) circuit connectome.



82304it [02:27, 559.70it/s]
100%|██████████| 82304/82304 [01:17<00:00, 1068.45it/s]


# Adapter Functionality

In this section we develop our adapter's functionality

In [4]:
adapter = BlueBrainCircuitAdapter()
cell_types_m = adapter.get_cell_types(mock_circuit_model, ("mtype",))
print(cell_types_m.head())
cell_types_me = adapter.get_cell_types(mock_circuit_model, ("mtype", "etype",) )
print(cell_types_me.head())

     mtype
0   L1_DAC
1  L1_SLAC
2   L23_MC
3  L23_ChC
4  L23_SBC
     mtype etype
0   L1_DAC  bNAC
1   L1_DAC   NAC
2  L1_SLAC  bNAC
3  L1_SLAC   NAC
4   L23_MC  bNAC


In [5]:
pathways = adapter.get_pathways(mock_circuit_model, ("mtype", "etype"))
print(pathways.shape)
assert pathways.shape[0] == cell_types_me.shape[0] ** 2
pathways.head()

(1444, 4)


pre_synaptic       post_synaptic      
         mtype etype         mtype etype
0       L1_DAC  bNAC        L1_DAC  bNAC
1       L1_DAC  bNAC        L1_DAC   NAC
2       L1_DAC  bNAC       L1_SLAC  bNAC
3       L1_DAC  bNAC       L1_SLAC   NAC
4       L1_DAC  bNAC        L23_MC  bNAC

In [7]:
pathways.iloc[1]

pre_synaptic   mtype    L1_DAC
               etype      bNAC
post_synaptic  mtype    L1_DAC
               etype       NAC
Name: 1, dtype: object

In [8]:
adapter.get_cells(mock_circuit_model,
                  **pathways.iloc[1].post_synaptic)\
        .etype\
        .unique()

array(['NAC'], dtype=object)

# Number of Afferent Connections

We develop an analysis of the number of afferent connections

In [9]:
from neuro_dmt.analysis.reporting import CheetahReporter
reporter_analyses =\
    CheetahReporter(
        path_output_folder=os.path.join(
            suite_connectome_analyses.path_reports,
            "analyses"))

We can also run our analyses over a chosen set of cell-types.

In [10]:
post_synaptic_cell =\
    suite_connectome_analyses\
        .random_cell(
            mock_circuit_model,
            adapter,
            {"mtype": "L23_MC"})
post_synaptic_cell

region                  S1Sh
layer                      2
nucleus          not-defined
mtype                 L23_MC
etype                   bNAC
morph_class      not-defined
synapse_class            INH
x                    47.7631
y                    185.226
z                    81.1804
gid                    62061
Name: 62061, dtype: object

In [11]:
gids_afferent =\
    adapter.get_afferent_gids(
        mock_circuit_model,
        post_synaptic_cell)

def soma_distance(pre_cells):
    return\
        suite_connectome_analyses.get_soma_distance_bins(
            mock_circuit_model,
            adapter,
            post_synaptic_cell, pre_cells)

pre_synaptic_cells =\
    adapter.get_cells(mock_circuit_model)\
           .loc[gids_afferent]
pre_synaptic_cells.head()
print(pre_synaptic_cells.shape[0])
#suite_connectome_analyses.get_soma_distance_bins(
#    mock_circuit_model,
#    adapter,
#    post_synaptic_cell, pre_synaptic_cells)
XYZ = ["x", "y", "z"]
print(post_synaptic_cell[XYZ].values)
print(type(pre_synaptic_cells[XYZ].values))
delta_position =\
    pre_synaptic_cells[XYZ].to_numpy(dtype=np.float64) - post_synaptic_cell[XYZ].to_numpy(dtype=np.float64)
print(delta_position.shape)
print(delta_position[0:2])
print(np.linalg.norm(post_synaptic_cell[XYZ]))
distance = np.linalg.norm(delta_position, axis=1)
print(len(distance))
distance
#distance =\
#    np.linalg.norm(
#        pre_synaptic_cells[XYZ].values - post_synaptic_cell[XYZ].values, 
#        axis=1)
#print(len(distance))
#soma_distance(pre_synaptic_cells)

187
[47.76305536600761 185.2257378634688 81.18035564403542]
<class 'numpy.ndarray'>
(187, 3)
[[146.17678936 -12.28080137 -22.38822396]
 [162.95856019 408.4281224  -33.22195874]]
207.79830020347816
187


array([ 148.3903784 ,  440.99061446,  459.49289662,  391.71273377,
        494.0429786 ,  476.65503577,  467.08051646,  525.31138284,
        796.85673426,  835.17271212,  886.43639265, 1010.17768949,
        638.09213638,  567.74598134, 1004.22846953,  943.00194039,
        637.25043754,  766.26411673,  647.11241746,  556.57915842,
        914.40133752,  577.31284119,  922.78434948,  812.58454255,
       1608.87903173, 1498.64505054, 1347.062372  , 1478.39146805,
       1057.91622163, 1313.39594953, 1457.40735294, 1031.78088924,
       1422.46453549, 1346.36621384, 1031.4072598 , 1363.36792552,
       1565.49433846, 1558.74377414, 1173.70280084, 1622.01562992,
       1089.10209614, 1177.0206314 , 1482.02805282, 1188.70738438,
       1642.75026418, 1489.67046115, 1118.72900064, 1033.23604763,
       1233.00832015, 1051.34563979, 1500.2055191 , 1195.05306932,
       1305.32021653, 1160.05788897,  417.9245068 ,  409.13203968,
        534.16054668,  406.204506  ,  529.65907157,  565.59716

In [12]:
suite_connectome_analyses =\
    ConnectomeAnalysesSuite(
        sample_size=20,
        cell_mtypes=["L5_TPC:A", "L5_TPC:B", "L5_UPC"])
m = suite_connectome_analyses\
    .number_afferent_connections(
        mock_circuit_model, adapter,
        {"mtype": "L23_MC"})

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/library/users/visood/sscx_dissemination/analyses/connectome/__init__.py Logger
DEBUGINFO@<2020-02-17 22:55:05>                                                 

            Number afferent connections for post-synaptic cell type: {'mtype': 'L23_MC'}
            

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/library/users/visood/sscx_dissemination/analyses/connectome/__init__.py Logger
INFO@<2020-02-17 22:55:05>                                                      
number_afferent_connections call count : 1



In [14]:
m.head()

(pre_synaptic_cell_type, mtype)  soma_distance
L1_DAC                           150.0            2.0
L23_ChC                          150.0            1.0
                                 250.0            1.0
                                 350.0            1.0
L23_MC                           150.0            1.0
Name: number_connections_afferent, dtype: float64

In [36]:
from tqdm import tqdm
connectome = mock_circuit_model.connectome
def iter_connections(pre=None, post=None):
    if pre is None:
        if post is not None:
            for post_gid in post:
                afferent_connections = connectome.afferent_connections.loc[post_gid]
                for _, cnxn in afferent_connections.iterrows():
                    yield (cnxn.pre_synaptic_cell_gid, post_gid, cnxn.strength)
        else:
            for _, cnxn in connectome.connections.iterrows():
                yield (cnxn.pre_synaptic_cell_gid, cnxn.post_synaptic_cell_gid, cnxn.strength)
    elif post is None:
        for pre_gid in pre:
            efferent_connections = connectome.efferent_connections.loc[pre_gid]
            for _, cnxn in efferent_connections.iterrows():
                yield (pre_gid, cnxn.post_synaptic_cell_gid, cnxn.strength)
            
    else:
        for pre_gid in pre:
            efferent_synapse_count =\
                connectome.synapse_count\
                          .loc[pre_gid]\
                          .reindex(post)\
                          .dropna()
            for post_gid, strength in efferent_synapse_count.iteritems():
                yield (pre_gid, post_gid, strength)

In [41]:
iterator =\
    iter_connections(post=[post_synaptic_cell.gid])
                    
df =\
    pd.DataFrame(
        [cnxn for cnxn in iterator],
        columns=["pre", "post", "strength"])
df

pre   post  strength
0      525  62587         5
1      768  62587         4
2      832  62587        10
3     1260  62587         2
4     1413  62587         4
..     ...    ...       ...
199  80484  62587         1
200  81335  62587         3
201  81816  62587         6
202  81857  62587         6
203  81908  62587         5

[204 rows x 3 columns]

In [40]:
pd.DataFrame(
    [cnxn for cnxn in iter_connections(pre=[post_synaptic_cell.gid])],
    columns=["pre", "post", "strength"])

pre   post  strength
0    62587    289         4
1    62587    501         4
2    62587    656         5
3    62587   1162         6
4    62587   1727         4
..     ...    ...       ...
181  62587  80333         4
182  62587  80601         3
183  62587  80854         3
184  62587  80981         2
185  62587  81720        10

[186 rows x 3 columns]

In [17]:
adapter.get_afferent_connections(mock_circuit_model, post_synaptic_cell)

pre_gid  strength
0        780         6
1       1539         6
2       2214         3
3       2348         5
4       2535         3
..       ...       ...
182    79365         2
183    80498         6
184    81130         7
185    81325         2
186    81593         4

[187 rows x 2 columns]

In [21]:
m = suite_connectome_analyses\
     .strength_afferent_connections(
        mock_circuit_model, adapter,
        {"mtype": "L23_MC"})

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/library/users/visood/sscx_dissemination/analyses/connectome/__init__.py Logger
DEBUGINFO@<2020-02-17 22:55:05>                                                 

            Strength afferent connections for post-synaptic cell type: {'mtype': 'L23_MC'}
            

/Users/vishalsoodmuchu/.vmgr_repo/py37/lib/python3.7/site-packages/neuro_dmt/library/users/visood/sscx_dissemination/analyses/connectome/__init__.py Logger
INFO@<2020-02-17 22:55:05>                                                      
strength_afferent_connections call count : 2



In [22]:
m.shape

(69,)

## SSCx variation

In [ ]:
report_connectome_analyses_bio_m =\
    suite_connectome_analyses\
        .analysis_number_afferent_connections(
            circuit_bio_m,
            adapter)


Because 60 post-synaptic mtypes can take too long, we can set the number of 
mtypes to process in one run:

In [ ]:
def get_layer_mtypes(circuit, query_layer):
    mtypes_all =\
        pd.Series(adapter.get_mtypes(circuit), name="mtype")
    return\
        list(mtypes_all[
                [query_layer in mtype for mtype in mtypes_all]
        ].values)
def analyze_number_afferent_connections(
        circuit,
        adapter,
        selected_mtypes,
        reporter,
        **kwargs):
    """..."""
    suite_connectome_analyses =\
        ConnectomeAnalysesSuite(
            sample_size=20,
            cell_mtypes=selected_mtypes)
    report=\
        suite_connectome_analyses\
            .analysis_number_afferent_connections(
                circuit, adapter, **kwargs)
    return reporter.post(report)

In [ ]:
analyze_number_afferent_connections(
    mock_circuit_model,
    adapter,
    ["L5_TPC:A", "L5_TPC:B",  "L5_UPC"],
    reporter_analyses,
    sample_size=200)

In [ ]:
suite_connectome_analyses =\
    ConnectomeAnalysesSuite(
        sample_size=20,
        cell_mtypes=["L23_MC"])
measurement_example =\
    suite_connectome_analyses\
        .analysis_number_afferent_connections\
        .get_measurement(
            mock_circuit_model,
            adapter)

In [ ]:
measurement_example["data"]